EnrollmentSystemWebApp/Controllers/PersonController.cs
using Audit.Mvc;
using Common;
using Common.AspNet.Logging;
using Common.Logging;
using Core.API.Model.Response;
using Domain.Custom_Models;
using EnrollmentSystemWebApp.Helpers;
using EnrollmentSystemWebApp.Proxy;
using Org.BouncyCastle.Asn1;
using Security.API.Model.Response;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace EnrollmentSystemWebApp.Controllers
{
    //[Audit(EventTypeName = "{controller}/{action} ({verb})", IncludeResponseBody = false, IncludeRequestBody = false)]
    [Authorize]
    public class PersonController : Controller
    {
        private CustomConfigurationLib config;
        private ICustomLog logger;
        private ProxyCoreAPI proxyCoreAPI;

        public PersonController()
        {
            config = new CustomConfigurationLib();
            logger = new CustomLog4Net();
            proxyCoreAPI = new ProxyCoreAPI();
        }

        // GET: Person
        public ActionResult SearchPerson()
        {
            EResponseBase<User_Response_v1> user = (EResponseBase<User_Response_v1>)Session[config.SessionUser];
            ViewBag.Usuario = user.objeto.FirstName;
            ViewBag.listOptions = user.objeto.listOptions;
            return View();
        }
        public ActionResult ConfigPeriod()
        {
            EResponseBase<User_Response_v1> user = (EResponseBase<User_Response_v1>)Session[config.SessionUser];
            ViewBag.Usuario = user.objeto.FirstName;
            ViewBag.listOptions = user.objeto.listOptions;
            return View();
        }

        public ActionResult ExportCsv()
        {
            EResponseBase<User_Response_v1> user = (EResponseBase<User_Response_v1>)Session[config.SessionUser];
            ViewBag.Usuario = user.objeto.FirstName;
            ViewBag.listOptions = user.objeto.listOptions;
            return View();
        }
        public ActionResult Settings()
        {
            EResponseBase<User_Response_v1> user = (EResponseBase<User_Response_v1>)Session[config.SessionUser];
            ViewBag.Usuario = user.objeto.FirstName;
            ViewBag.listOptions = user.objeto.listOptions;
            return View();
        }
        public ActionResult Reports()
        {
            EResponseBase<User_Response_v1> user = (EResponseBase<User_Response_v1>)Session[config.SessionUser];
            ViewBag.Usuario = user.objeto.FirstName;
            ViewBag.listOptions = user.objeto.listOptions;
            return View();
        }

        public ActionResult ReportsWeb()
        {
            EResponseBase<User_Response_v1> user = (EResponseBase<User_Response_v1>)Session[config.SessionUser];
            ViewBag.Usuario = user.objeto.FirstName;
            ViewBag.listOptions = user.objeto.listOptions;
            return View();
        }

        public ActionResult ReportsSystem()
        {
            EResponseBase<User_Response_v1> user = (EResponseBase<User_Response_v1>)Session[config.SessionUser];
            ViewBag.Usuario = user.objeto.FirstName;
            ViewBag.listOptions = user.objeto.listOptions;
            return View();
        }
        public ActionResult ReportsEnrollment()
        {
            EResponseBase<User_Response_v1> user = (EResponseBase<User_Response_v1>)Session[config.SessionUser];
            ViewBag.Usuario = user.objeto.FirstName;
            ViewBag.listOptions = user.objeto.listOptions;
            return View();
        }
        public ActionResult ReportsDisenrollment()
        {
            EResponseBase<User_Response_v1> user = (EResponseBase<User_Response_v1>)Session[config.SessionUser];
            ViewBag.Usuario = user.objeto.FirstName;
            ViewBag.listOptions = user.objeto.listOptions;
            return View();
        }
        public ActionResult ReportsJustcause()
        {
            EResponseBase<User_Response_v1> user = (EResponseBase<User_Response_v1>)Session[config.SessionUser];
            ViewBag.Usuario = user.objeto.FirstName;
            ViewBag.listOptions = user.objeto.listOptions;
            return View();
        }

        public ActionResult ReportsCallCenter()
        {
            EResponseBase<User_Response_v1> user = (EResponseBase<User_Response_v1>)Session[config.SessionUser];
            ViewBag.Usuario = user.objeto.FirstName;
            ViewBag.listOptions = user.objeto.listOptions;
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> GetPeopleByFilters(MemberRequestV2 request)
        {

            Transaction transaction = string.Empty.GetTransaction();
            InitializeLogger(transaction);
            Common.EResponseBase<MemberResponseV6> response = await proxyCoreAPI.GetPeopleByFilters(transaction, logger, config, null, request);
            int recordsTotal = 0;
            List<MemberResponseV6> records = null;
            if (response.Code == config.CodigoExito)
            {
                records = new List<MemberResponseV6>();

                records = response.listado.ToList();
                recordsTotal = records.Count;
                return Json(new
                {
                    code = response.Code,
                    message = response.Message,
                    recordsTotal = recordsTotal,
                    records = records
                }
                );
            }
            else
            {
                return Json(new
                {
                    code = response.Code,
                    message = response.Message,
                    recordsTotal = recordsTotal,
                    records = records
                });
            }
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<ActionResult>  GetByFilters(string Last4SSN="", string DateOfBirth= "")
        {

            Transaction transaction = string.Empty.GetTransaction();
            InitializeLogger(transaction);
            string url = string.Empty;

            MemberRequestV2 request = new MemberRequestV2
            {
                Last4SSN = Last4SSN,
                DateOfBirth =DateOfBirth=="" ? DateTime.MinValue : Convert.ToDateTime( DateOfBirth)
            };
            Common.EResponseBase<MemberResponseV6> response = await proxyCoreAPI.GetPeopleByFilters(transaction, logger, config, null, request);

            if (response.listado != null && response.listado.ToList().Count > 0)
                url =string.Concat(config.urlMembers, response.listado.FirstOrDefault().Id.ToString());           
             
            return Json(new{url = url }, JsonRequestBehavior.AllowGet);

        }
       

        [HttpPost]
        public async Task<ActionResult> ChangePersonMco(MemberRequestV1 request)
        {
            bool isEnabled = (request.IsJustCause) ? (bool)Session[config.ChangeEnrollmentEnabledJustCause] : (bool)Session[config.ChangePersonMcoEnabled];
            if (isEnabled)
            {
                Transaction transaction = string.Empty.GetTransaction();
                InitializeLogger(transaction);
                EResponseBase<User_Response_v1> user = (EResponseBase<User_Response_v1>)Session[config.SessionUser];
                request.UserName = user.objeto.FirstName;
                Common.EResponseBase<MemberResponseV1> response = await proxyCoreAPI.ChangePersonMco(transaction, logger, config, null, request);
                int recordsTotal = 0;
                MemberResponseV1 record = null;
                //TODO: HOMAR Quitar
                //response.Code = 0;
                if (response.Code == config.CodigoExito)
                {
                    record = new MemberResponseV1();
                    record = response.objeto;
                    Session[config.SessionEnrollmentHistory] = record.EnrollmentHistoryID;
                    recordsTotal = (record != null ? 1 : 0);
                    return Json(new
                    {
                        code = response.Code,
                        message = response.Message,
                        recordsTotal = recordsTotal,
                        records = record
                    }
                    );
                }
                else
                {
                    return Json(new
                    {
                        code = response.Code,
                        message = response.Message,
                        recordsTotal = recordsTotal,
                        records = record
                    });
                }
            }
            else
            {
                return Json(new
                {
                    code = -1000
                });
            }
        }
        [HttpPost]
        public async Task<ActionResult> ChangePersonMcoReject(MemberRequestV1 request)
        {
            Transaction transaction = string.Empty.GetTransaction();
            InitializeLogger(transaction);
            Common.EResponseBase<MemberResponseV1> response = await proxyCoreAPI.ChangePersonMcoReject(transaction, logger, config, null, request);
            int recordsTotal = 0;
            MemberResponseV1 record = null;
            //TODO: HOMAR Quitar
            //response.Code = 0;
            if (response.Code == config.CodigoExito)
            {
                record = new MemberResponseV1();
                record = response.objeto;
                Session[config.SessionEnrollmentHistory] = record.EnrollmentHistoryID;
                recordsTotal = (record != null ? 1 : 0);
                return Json(new
                {
                    code = response.Code,
                    message = response.Message,
                    recordsTotal = recordsTotal,
                    records = record
                }
                );
            }
            else
            {
                return Json(new
                {
                    code = response.Code,

EnrollmentSystemWebApp/Controllers/ReportController.cs
using Audit.Mvc;
using Common.AspNet.Logging;
using Common.Logging;
using Core.API.Model.Request;
using Core.API.Model.Response;
using Domain.Custom_Models;
using EnrollmentSystemWebApp.Helpers;
using EnrollmentSystemWebApp.Proxy;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace EnrollmentSystemWebApp.Controllers
{
    //[Audit(EventTypeName = "{controller}/{action} ({verb})", IncludeResponseBody = false, IncludeRequestBody = false)]
    [Authorize]
    public class ReportController : Controller
    {
        private CustomConfigurationLib config;
        private ICustomLog logger;
        private ProxyCoreAPI proxyCoreAPI;

        public ReportController()
        {
            config = new CustomConfigurationLib();
            logger = new CustomLog4Net();
            proxyCoreAPI = new ProxyCoreAPI();
        }

        [HttpPost]
        public async Task<ActionResult> GetReportInscripciones(ReportRequestV1 request)
        {

            Transaction transaction = string.Empty.GetTransaction();
            InitializeLogger(transaction);
            Common.EResponseBase<ReportResponseV1> response = await proxyCoreAPI.GetReportInscripciones(transaction, logger, config, null, request);
            int recordsTotal = 0;
            //List<ReportResponseV1> records = null;
            ReportResponseV1 record = null;
            if (response.Code == config.CodigoExito)
            {
                //records = new List<ReportResponseV1>();

                //records = response.listado.ToList();
                //recordsTotal = records.Count;
                record = new ReportResponseV1();

                record = response.objeto;
                recordsTotal = (record != null ? 1 : 0);
                return Json(new
                {
                    code = response.Code,
                    message = response.Message,
                    recordsTotal = recordsTotal,
                    records = record
                }
                );
            }
            else
            {
                return Json(new
                {
                    code = response.Code,
                    message = response.Message,
                    recordsTotal = recordsTotal,
                    records = record
                });
            }
        }

        [HttpPost]
        public async Task<ActionResult> GetReportJustaCausa(ReportRequestV1 request)
        {

            Transaction transaction = string.Empty.GetTransaction();
            InitializeLogger(transaction);
            Common.EResponseBase<ReportResponseV1> response = await proxyCoreAPI.GetReportJustaCausa(transaction, logger, config, null, request);
            int recordsTotal = 0;
            ReportResponseV1 record = null;
            if (response.Code == config.CodigoExito)
            {
                record = new ReportResponseV1();

                record = response.objeto;
                recordsTotal = (record != null ? 1 : 0);
                return Json(new
                {
                    code = response.Code,
                    message = response.Message,
                    recordsTotal = recordsTotal,
                    records = record
                }
                );
            }
            else
            {
                return Json(new
                {
                    code = response.Code,
                    message = response.Message,
                    recordsTotal = recordsTotal,
                    records = record
                });
            }
        }

        private void InitializeLogger(Transaction transaction)
        {
            logger.InitializeLog(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType, transaction);
        }
    }
}

EnrollmentSystemWebApp/Controllers/ReportsController.cs
using Common.AspNet.Logging;
using Common.Logging;
using Domain.Custom_Models;
using EnrollmentSystemWebApp.Helpers;
using EnrollmentSystemWebApp.Proxy;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace EnrollmentSystemWebApp.Controllers
{
    [Authorize]
    public class ReportsController : Controller
    {
        private CustomConfigurationLib config;
        private ICustomLog logger;
        private ProxyCoreAPI proxyCoreAPI;

        public ReportsController()
        {
            config = new CustomConfigurationLib();
            logger = new CustomLog4Net();
            proxyCoreAPI = new ProxyCoreAPI();
        }

        private void InitializeLogger(Transaction transaction)
        {
            logger.InitializeLog(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType, transaction);
        }

        [HttpPost]
        public async Task<ActionResult> GetReportsWeb(StatisticsRequestV1 request)
        {

            Transaction transaction = string.Empty.GetTransaction();
            InitializeLogger(transaction);
            Common.EResponseBase<Core.API.Model.Response.StatisticsResponseV1> response = await proxyCoreAPI.GetReportsWeb(transaction, logger, config, null, request);
            int recordsTotal = 0;
            List<EnrollmentPeriodResponseV1> records = null;
            if (response.Code == config.CodigoExito)
            {
                return Json(response);
            }
            else
            {
                return Json(new
                {
                    code = response.Code,
                    message = response.Message,
                    recordsTotal = recordsTotal,
                    records = records
                });
            }
        }

        [HttpPost]
        public async Task<ActionResult> InsertStatistic(int typeId)
        {
            StatisticsRequestV1 request = new StatisticsRequestV1
            {
                TypeId = typeId
            };

            Transaction transaction = string.Empty.GetTransaction();
            InitializeLogger(transaction);
            Common.EResponseBase<Core.API.Model.Response.StatisticsResponseV1> response = await proxyCoreAPI.InsertStatistic(transaction, logger, config, null, request);
            int recordsTotal = 0;
            List<EnrollmentPeriodResponseV1> records = null;
            if (response.Code == config.CodigoExito)
            {
                return Json(response);
            }
            else
            {
                return Json(new
                {
                    code = response.Code,
                    message = response.Message,
                    recordsTotal = recordsTotal,
                    records = records
                });
            }
        }
    }
}

EnrollmentSystemWebApp/Views/Person/ExportCsv.cshtml
<main>



    <div class="body-content">

        <main>

            @*<label class="tab" for="tab1" data-i18n="Expense_Settings_Tag">Settings</label>*@
            <section id="content1" level-id="1">
                <div class="m-bottom20px">
                    <hr style="height: 1px;border: 0;box-shadow: 0 10px 5px -10px #8c8b8b inset;margin: 0 0 15px 0;">
                    <div id="Container_Main" style="padding: 20px;">


                        <div class="row">
                            <div class="col-md-12">
                                <label class="Tittle_Settings_Main" style="display:block;margin-bottom:10px;font-weight: bold;" data-i18n="Person_export_History">Export History</label>
                                <label class="Tittle_Settings_secondLine" style="display:block;margin-left:20px;margin-bottom:10px;" data-i18n="Person_export" >Export</label>

                                <div class="Container_Controls" style="display:block;margin-left:40px;margin-bottom:10px;">
                                    <div class="form-group col-md-2">
                                        <label data-i18n="Person_export_date_from">Date From:</label>
                                        <div class="position-relative has-icon-left">
                                            <input type='text' id="DateFrom" class="form-control" placeholder="mm/dd/yyyy" style="background-color: white;" />
                                            <div class="form-control-position">
                                                <i class="icon-calendar"></i>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group col-md-2">
                                        <label data-i18n="Person_export_date_to">Date To:</label>
                                        <div class="position-relative has-icon-left">
                                            <input type='text' id="DateTo" class="form-control" placeholder="mm/dd/yyyy" style="background-color: white;" />
                                            <div class="form-control-position">
                                                <i class="icon-calendar"></i>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group col-md-2">
                                        <div style="  margin-top: 8px;">
                                            <label for=""></label>
                                            <div class="position-relative has-icon-left">
                                                <button class="btn btn-success" id="btnExport" type="submit" data-i18n="Person_settings_exportar_csv">Export to CSV</button>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
            </section>
        </main>
        <div class="modal fade" id="modalCart" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document" style="max-width: 800px;">
                <div class="modal-content">
                    <!--Header-->
                    <!--Body-->
                    <!--Footer-->

                </div>
            </div>
        </div>
        <hr>
        <div class="footer grey">

        </div>
    </div>
</main>
<script>
    @* Variables to use in SearchPerson.js *@
    var urlGetHistoryByFilters = '@Url.Action("GethistoryByFilters", "Enrollment")';

    @*var urlGetApplicationMembers = '@Url.Action("GetApplicationMembers", "Person")';*@
    var urlEnrollmentPage = '@Url.Action("Enrollment", "Enrollment")';
</script>
<script>
    $("#settings").attr({
        class: "active"
    });
</script>
<script src="~/app-assets/assets/js/Settings.js"></script>

EnrollmentSystemWebApp/Views/Person/Reports.cshtml
<link href="~/app-assets/assets/css/CustomCards.css" rel="stylesheet" />
<div class="container">
    <div class="row">
        <div class="col-md-4 col-xs-12">
            <div class="card horizontal customCard">
                <div class="ch-grid">
                    <div class="ch-item ch-img-6" onclick="window.location.href = '@Url.Action("ReportsWeb", "Person")';">
                        <div class="ch-info ch-info-1">
                            <img class="img-rounded" src="~/app-assets/assets/images/4288565analysisanalyticschartdatapie-115791_115722.png" />
                        </div>
                    </div>
                </div>
                <div class="card-stacked">
                    <div class="card-content">
                        <h3 data-i18n="Person_reports_web_applications">Web Aplications Report</h3>
                    </div>
                </div>
            </div>
        </div>
        @*<div class="col-md-4 col-xs-12">
            <div class="card horizontal customCard">
                <div class="ch-grid">
                    <div class="ch-item ch-img-7" onclick="window.location.href = '@Url.Action("ReportsSystem", "Person")';">
                        <div class="ch-info ch-info-2">
                            <img class="img-rounded" src="~/app-assets/assets/images/4288565analysisanalyticschartdatapie-115791_115722.png" />
                        </div>
                    </div>
                </div>
                <div class="card-stacked">
                    <div class="card-content">
                        <h3 data-i18n="Person_reports_system_downtime">System Downtime Report</h3>
                    </div>
                </div>
            </div>
        </div>*@
        <div class="col-md-4 col-xs-12">
            <div class="card horizontal customCard">
                <div class="ch-grid">
                    <div class="ch-item ch-img-8" onclick="window.location.href = '@Url.Action("ReportsEnrollment", "Person")';">
                        <div class="ch-info ch-info-3">
                            <img class="img-rounded" src="~/app-assets/assets/images/4288565analysisanalyticschartdatapie-115791_115722.png" />
                        </div>
                    </div>
                </div>
                <div class="card-stacked">
                    <div class="card-content">
                        <h3 data-i18n="Person_reports_enrollment">Enrollment Report</h3>
                    </div>
                </div>
            </div>
        </div>
        @*<div class="col-md-4 col-xs-12">
            <div class="card horizontal customCard">
                <div class="ch-grid">
                    <div class="ch-item ch-img-2">
                        <div class="ch-info ch-info-3" onclick="window.location.href = '@Url.Action("ReportsDisenrollment", "Person")';">
                            <img class="img-rounded" src="~/app-assets/assets/images/icon-Network.svg" />
                        </div>
                    </div>
                </div>
                <div class="card-stacked">
                    <div class="card-content">
                        <h3 data-i18n="Person_reports_disenrollment">Disenrollment Report</h3>
                    </div>
                </div>
            </div>
        </div>*@
        <div class="col-md-4 col-xs-12">
            <div class="card horizontal customCard">
                <div class="ch-grid">
                    <div class="ch-item ch-img-9">
                        <div class="ch-info ch-info-3" onclick="window.location.href = '@Url.Action("ReportsJustcause", "Person")';">
                            <img class="img-rounded" src="~/app-assets/assets/images/4288565analysisanalyticschartdatapie-115791_115722.png" />
                        </div>
                    </div>
                </div>
                <div class="card-stacked">
                    <div class="card-content">
                        <h3 data-i18n="Person_reports_just_cause">Just Cause Report</h3>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4 col-xs-12">
            <div class="card horizontal customCard">
                <div class="ch-grid">
                    <div class="ch-item ch-img-9">
                        <div class="ch-info ch-info-3" onclick="window.location.href = '@Url.Action("ReportsCallCenter", "Person")';">
                            <img class="img-rounded" src="~/app-assets/assets/images/4288565analysisanalyticschartdatapie-115791_115722.png" />
                        </div>
                    </div>
                </div>
                <div class="card-stacked">
                    <div class="card-content">
                        <h3 data-i18n="Person_reports_callcenter">Call Center Report</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
     $("#reports").attr({
            class: "active",
     });
</script>
@*<div class="row">
        <div class="col-md-4 col-xs-12">
            <div class="card horizontal customCard">
                <div class="ch-grid">
                    <div class="ch-item ch-img-4">
                        <div class="ch-info ch-info-4">
                            <img src="~/app-assets/assets/images/icon-Navigation.svg" />
                        </div>
                    </div>
                </div>
                <div class="card-stacked">
                    <div class="card-content">
                        <h3 data-i18n="Index_Search_PCP/PCM">Buscar PCP/PMG</h3>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4 col-xs-12">
            <div class="card horizontal customCard">
                <div class="ch-grid">
                    <div class="ch-item ch-img-5">
                        <div class="ch-info ch-info-5">
                            <img src="~/app-assets/assets/images/icon-Report.svg" />
                        </div>
                    </div>
                </div>
                <div class="card-stacked">
                    <div class="card-content">
                        <h3 data-i18n="Index_Reporting">Reportes</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>*@
<script src="~/app-assets/assets/js/CustomCards.js"></script>

EnrollmentSystemWebApp/Views/Person/ReportsJustcause.cshtml
<link href="~/app-assets/assets/css/CustomCards.css" rel="stylesheet" />

<!-- font icons-->
<!-- END VENDOR CSS-->
<!-- BEGIN ROBUST CSS-->
<link rel="stylesheet" type="text/css" href="~/app-assets/css/bootstrap-extended.css">
<link rel="stylesheet" type="text/css" href="~/app-assets/css/app.css">
<link rel="stylesheet" type="text/css" href="~/app-assets/css/colors.css">
<link rel="stylesheet" type="text/css" href="~/app-assets/css/icomoon.css">
<!-- END ROBUST CSS-->
<!-- BEGIN Page Level CSS-->

<div>

    <div class="col-md-12" style="margin-top: 30px ; margin-left: 30px">
        <label class="Tittle_Settings_Main" style="display:block;margin-bottom:10px;font-weight: bold;" data-i18n="Person_Filters">Filters</label>
        <label class="Tittle_Settings_secondLine" style="display:block;margin-left:20px;margin-bottom:10px;" data-i18n=""></label>

        <div class="Container_Controls" style="display:block;margin-left:40px;margin-bottom:10px;">
            <div class="form-group col-md-4">
                <label data-i18n="Person_Date">Date:</label>
                <div class="position-relative has-icon-left">
                    <input type='text' id="DateFilter" class="form-control" placeholder="mm/dd/yyyy" />
                    <div class="form-control-position">
                        <i class="icon-calendar"></i>
                    </div>
                </div>
            </div>

            <div class="form-group col-md-4">
                <div style=" margin: 0 10px;margin-top: 8px;">
                    <label for=""></label>
                    <div class="position-relative has-icon-left">
                        <button class="btn btn-success" id="btnBuscar" type="submit" data-i18n="Person_Filter">Filter</button>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <div class="col-md-4 col-xs-12">
        <div class="col-xs-12">

            <div class="card-header">
                <h4 class="card-title">Aprobaciones de Justa Causa por Centro de Llamadas</h4>
                <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>

            </div>
            <div class="card-body collapse in">
                <div class="card-block">
                    <div id="stacked-column-chart"></div>
                </div>
            </div>

        </div>



    </div>
    <div class="col-md-4 col-xs-12">


        <!-- Stacked Column Chart -->

        <div class="col-xs-12">
            <div>
                <div class="card-header">
                    <h4 class="card-title">Aprobaciones de Justa Causa en sitio</h4>
                    <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>

                </div>
                <div class="card-body collapse in">
                    <div class="card-block">
                        <div id="stacked-column-chart2"></div>
                    </div>
                </div>
            </div>
        </div>



    </div>
    <div class="col-md-4 col-xs-12">


        <!-- Stacked Column Chart -->

        <div class="col-xs-12">
            <div>
                <div class="card-header">
                    <h4 class="card-title">Aprobaciones de Justa Causa por ASES</h4>
                    <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>

                </div>
                <div class="card-body collapse in">
                    <div class="card-block">
                        <div id="stacked-column-chart3"></div>
                    </div>
                </div>
            </div>
        </div>



    </div>
</div>

<script>

    var urlGetReportJustaCausa = '@Url.Action("GetReportJustaCausa", "Report")';

        var results_cbTypeExpense = [];
        var results_cbStateExpense = [];
        var lst_Projects = [];



</script>
<script src="https://www.google.com/jsapi" type="text/javascript"></script>
<script src="~/app-assets/assets/js/CustomCards.js"></script>
<script src="~/app-assets/assets/js/ReportJustaCausa.js"></script>