EnrollmentPrincipalWebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EnrollmentPrincipalWebApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Aseguradoras()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

EnrollmentPrincipalWebApp/Controllers/PrincipalController.cs
using Common;
using Common.AspNet.Logging;
using Common.HttpHelpers;
using Common.Logging;
using EnrollmentPrincipalWebApp.Helpers;
using EnrollmentPrincipalWebApp.Proxy;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc; 
using Common.Logging;
using Common;
using Common.HttpHelpers;
using EnrollmentPrincipalWebApp.Helpers;
using Common.AspNet.Logging;
using System;
using EnrollmentPrincipalWebApp.Proxy;
using System.Configuration;

namespace EnrollmentPrincipalWebApp.Controllers
{

    public class PrincipalController : Controller
    {
        CustomConfigurationLib config;
        // Pages in Spanish 
        //Test Homar Dávila
        //Test Homar Dávila 2
        //Test Homar Dávila 3
        public PrincipalController()
        {
            config = new CustomConfigurationLib();
        }

        public ActionResult Index()
        {
            ReportsController ctrl = new ReportsController();
            _ = ctrl.InsertStatistic(2);
            ViewBag.SelfServices = config.SelftService_SelftServices;
            ViewBag.Logos = true;
            ViewBag.BusquedaProveedores = config.SelftService_BusquedaProveedores;
            ViewBag.UrlCensos = config.UrlCensos;
            ViewBag.ModalEnabled = config.ModalEnabled;
            ViewBag.ModalTitle = config.ModalTitleES;
            ViewBag.ModalMsg = config.ModalMsgES;
            ViewBag.ModalMsg2 = config.ModalMsg2ES;
            return View();
        }

        public  ActionResult IndexNA()
        {
            ReportsController ctrl = new ReportsController();
            _ = ctrl.InsertStatistic(2);
            ViewBag.SelfServices = config.SelftService_SelftServices;
            ViewBag.Logos = true;
            ViewBag.BusquedaProveedores = config.SelftService_BusquedaProveedores;
            ViewBag.UrlCensos = config.UrlCensos;
            ViewBag.ModalEnabled = config.ModalEnabled;
            ViewBag.ModalTitle = config.ModalTitleEN;
            ViewBag.ModalMsg = config.ModalMsgEN;
            ViewBag.ModalMsg2 = config.ModalMsg2EN;
            return View();
        }

        public ActionResult PanoramaGeneral()
        {
            ViewBag.SelfServices = config.SelftService_SelftServices;
            return View();
        }

        public ActionResult PuntosDestacadosDetalles()
        {
            ViewBag.SelfServices = config.SelftService_SelftServices;
            return View();
        }

        public ActionResult BusquedaProveedores()
        {
            ViewBag.BusquedaProveedores = config.SelftService_BusquedaProveedores;
            ViewBag.SelfServices = config.SelftService_SelftServices;
            //"http://52.20.56.7/EnrollmentSelfServices/Home/IndexNA/";
            return View();
        }

        public ActionResult UbicacionOficinas()
        {
            ViewBag.SelfServices = config.SelftService_SelftServices;
            return View();
        }

        public ActionResult CambiarMco()
        {
            ViewBag.SelfServices = config.SelftService_SelftServices;

            return View();
        }

        public ActionResult HacerCita()
        {
            ViewBag.SelfServices = config.SelftService_SelftServices;
            ViewBag.HacerCita = config.Url_HacerCitas;
            //ViewBag.HacerCita = WebConfigurationManager.AppSettings["HacerCita"].ToString();
            //"http://3.226.62.144/VitalQ.citas";
            return View();
        }
        public ActionResult ContactaAseguradora()
        {
            ViewBag.SelfServices = config.SelftService_SelftServices;
            return View();
        }

        // Pages in English 

        public ActionResult English()
        {
            ViewBag.SelfServices = config.SelftService_SelftServices;
            return View();
        }

        public ActionResult Overview()
        {
            ViewBag.SelfServices = config.SelftService_SelftServices;
            return View();
        }

        public ActionResult DetailHighlights()
        {
            ViewBag.SelfServices = config.SelftService_SelftServices;
            return View();
        }

        public ActionResult ProviderSearch()
        {
            ViewBag.BusquedaProveedores = config.SelftService_BusquedaProveedores;
            ViewBag.SelfServices = config.SelftService_SelftServices;
            return View();
        }

        public ActionResult OfficeLocations()
        {
            ViewBag.SelfServices = config.SelftService_SelftServices;
            return View();
        }

        public ActionResult ChangeMco()
        {
            ViewBag.SelfServices = config.SelftService_SelftServices;
            return View();
        }

        public ActionResult MakeAppointment()
        {
            ViewBag.SelfServices = config.SelftService_SelftServices;
            ViewBag.HacerCita = config.Url_HacerCitas;
            return View();
        }
        public ActionResult ContactInsurer()
        {
            ViewBag.SelfServices = config.SelftService_SelftServices;
            return View();
        }

    }

}

EnrollmentPrincipalWebApp/Controllers/ReportsController.cs
using Common.AspNet.Logging;
using Common.Logging;
using Domain.Custom_Models;
using EnrollmentPrincipalWebApp.Helpers;
using EnrollmentPrincipalWebApp.Proxy;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace EnrollmentPrincipalWebApp.Controllers
{
    public class ReportsController : Controller
    {
        private CustomConfigurationLib config;
        private ICustomLog logger;
        private ProxyCoreAPI proxyCoreAPI;

        public ReportsController()
        {
            config = new CustomConfigurationLib();
            logger = new CustomLog4Net();
            proxyCoreAPI = new ProxyCoreAPI();
        }

        private void InitializeLogger(Transaction transaction)
        {
            logger.InitializeLog(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType, transaction);
        }

        [HttpPost]
        public async Task<ActionResult> InsertStatistic(int typeId)
        {
            StatisticsRequestV1 request = new StatisticsRequestV1
            {
                TypeId = typeId
            };

            Transaction transaction = string.Empty.GetTransaction();
            InitializeLogger(transaction);
            Common.EResponseBase<Core.API.Model.Response.StatisticsResponseV1> response = await proxyCoreAPI.InsertStatistic(transaction, logger, config, null, request);
            int recordsTotal = 0;
            List<EnrollmentPeriodResponseV1> records = null;
            if (response.Code == config.CodigoExito)
            {
                return Json(response);
            }
            else
            {
                return Json(new
                {
                    code = response.Code,
                    message = response.Message,
                    recordsTotal = recordsTotal,
                    records = records
                });
            }
        }
    }
}

EnrollmentPrincipalWebApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

EnrollmentPrincipalWebApp/Views/Home/Aseguradoras.cshtml
@{
    ViewBag.Title = "Aseguradoras";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row text-center align-items-center" style="height:200px;background-color:#0092BC;">

    <div class="col-md-4"></div>
    <div class="col-md-4">        
            <h2 style="color:white">
                ¿Necesitas cambiar tu aseguradora?
            </h2>
        
    </div>
    <div class="col-md-4"></div>

</div>

<div class="row" style="height:400px;background-color:white;padding-top: 4rem;">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <div class="card-deck text-center">
            <div class="card align-items-center" style="width: 18rem;">

                <img class="card-img-top" src="~/wwwroot/images/responsive.svg" alt="Card image cap" style=" width:128px;" />
                <div class="card-body align-items-center">
                    <h5 class="card-title" style="color:#0092BC; font-weight:bold">Personal Administrativo</h5>
                    <a href="http://localhost:6010/Enrollment" class="btn btn-primary" style="color:white">Más Información</a>
                    @*<a href="http://localhost:6010/Enrollment" class="btn btn-primary" style="color:white">Más Información</a>*@
                </div>
            </div>
         

            <div class="card align-items-center" style="width: 18rem;">
                <img class="card-img-top" src="~/wwwroot/images/student.svg" alt="Card image cap" style=" width:128px;">
                <div class="card-body">
                    <h5 class="card-title" style="color:#0092BC; font-weight:bold">Haz tu mismo el cambio</h5>
                    <a href="http://localhost:58499/ErnollmentSelfServices/User/Login" class="btn btn-primary" style="color:white">Más Información</a>
                    @*<a href="http://localhost:58499/ErnollmentSelfServices/User/Login" class="btn btn-primary" style="color:white">Más Información</a>*@
                </div>
            </div>

        </div>
    </div>
    <div class="col-md-2"></div>
</div>

<div class="row text-center align-items-center" style="height:20px;background-color:#0092BC;">

&nbsp;    

</div>

EnrollmentPrincipalWebApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

EnrollmentPrincipalWebApp/Views/Home/Index - Copia.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

EnrollmentPrincipalWebApp/Views/Principal/ChangeMco.cshtml
@{
    ViewBag.Title = "Select Your Preferred Insurer (MCO)";
    Layout = "~/Views/Shared/_Layout-Principal-English.cshtml";
    ViewBag.Ruta = "CambiarMco";
}

<main>
    <div class="container">
        <div class="row">
            <div class="col-12 mb-5">
            </div>
            <div class="col">
                <h1>Select Your Preferred Insurer (MCO)</h1>
                <p>
                    <strong>Ready to change your Insurer (MCO)?</strong><br>
                    If you are ready to change your Insurer (MCO) and you confirmed your preferred primary care physician (PCP) and primary medical group (PMG) is in the Insurer's network, <span class="titulo--secundario">log in now</span>  to change your Insurer.
                </p>

                <p><a class="btn btn-lg btn-info sso-link btn_LoginSelfEnrollment" role="button" href="@ViewBag.SelfServices" target="_blank">Log In Now</a></p>

                <p>
                    <strong>Please note:</strong><br>
                    We will need to keep your information secure and protected. You will be asked to enter:
                </p>
                <ul>
                    <li>Last four digits of your Social Security Number</li>
                    <li>Birth date</li>
                    <li>ZIP Code</li>
                </ul>
                <p>After the above information is confirmed, you will be asked to create a user identification and password before you can log in and change your Insurer.</p>
                <!-- <h4 class="heading--gray">Resource downloads</h4>
                <p><a href="pdf/pdf-placeholder.pdf">Steps to change Insurer (MCO)</a></p> -->
                <h4 class="heading--gray">Questions</h4>
                <p>Contact the VITAL Counseling Center at <strong>1-833-253-7721</strong> free of charge Monday through Friday from 8:00 a.m. to 6:00 p.m.</p>
                <p>TTY/TDD service is available only for Audio Impaired at <strong>1-888-984-0128</strong>.</p>
            </div>
            <div class="col-lg-3">
            </div>
        </div>
    </div>
</main>

EnrollmentPrincipalWebApp/Views/Principal/Index.cshtml
@{
    ViewBag.Title = "";
    ViewBag.Ruta = @Url.Action("IndexNA", "Principal");
}
<style>
    #Principal {
        position: relative;
        color: white;
    }


    /*.titulo--principal {
        color: #0089b5;
        font-size: 4.2em;
        margin: 0.1em 0 0.5em;
    }*/

    #Principal {
        height: 430px;
        width: 100%;
        overflow: hidden;
    }

    #imgPrincipal {
        min-width: 100%;
        object-fit: cover;
    }

    ul {
        list-style-type: square;
    }

    .carousel-caption-custom {
        position: absolute;
        right: 15%;
        bottom: 105px;
        /*left: 15%;*/
        z-index: 10;
        padding-top: 20px;
        padding-bottom: 20px;
        color: #fff;
        text-align: center;
        text-shadow: 0 1px 2px rgba(0, 0, 0, .6);
    }
</style>
<main>
    <div class="clearfix"></div>
    <div class="container">
        <div class="row" id="Principal">
            <img id="imgPrincipal" class="d-none d-lg-block" src="~/wwwroot/assets/img/Principal.jpg" style="width:100%; max-height:500px; overflow:hidden">
            <img id="imgPrincipal" class="d-none d-md-block d-lg-none" src="~/wwwroot/assets/img/Principal-m.jpg" style="width:100%; max-height:500px; overflow:hidden">
            <img id="imgPrincipal" class="d-md-none" src="~/wwwroot/assets/img/Principal-m2.jpg" style="width:100%; max-height:500px; overflow:hidden">
            <div class="card-body center-left">
                <h2 class="titulo--principal align-middle">
                    <span>TÚ ELIGES</span>
                    <br />
                    <span>tu aseguradora</span>
                    @*<br />
                        <span> de seguro</span>*@
                </h2>
            </div>
        </div>
        <br />
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-5 col-lg-5 nopadding d-none d-lg-block">
                <img src="~/wwwroot/assets/img/Principal2.jpg" style="width:100%; height:100%;">
            </div>
            <div class="col-md-7 col-lg-7 nopadding">
                <div class="card-body card__principal h-100">
                    <div class="text-left" style="font-size:1em;">
                        <p class="titulo--secundario">El Periodo Anual de Inscripci&oacute;n Abierta ser&aacute; del 1 de noviembre al 15 de diciembre de 2020.</p>
                        <p>Durante esos 45 d&iacute;as usted podr&aacute; cambiar de aseguradora, si as&iacute; lo desea, oprima <a href="~/Principal/CambiarMco">aqu&iacute;</a>. Si usted desea permanecer con la aseguradora que tiene actualmente, no tiene que realizar ning&uacute;n cambio.</p>
                        <ul class="texto--contenido" style="line-height:20px;">
                            <li>Si necesita hacer un cambio de PMG o de PCP solamente, puede comunicarse con la aseguradora (MCO) que usted seleccion&oacute;.</li>
                            <li>Si tiene preguntas con relaci&oacute;n a su tarjeta de plan m&eacute;dico, puede llamar a la aseguradora o visitar un centro de servicios. (Ver n&uacute;meros de tel&eacute;fono abajo)</li>
                            <li>Para servicio TTY debe llamar al 1-888-984-0128.</li>
                            <li>Si necesita informaci&oacute;n sobre su cita para recertificarse, puede llamar al 787-641-4224.</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="card-body card__principal">
                <div class="row">
                    <div class="col-xl-2 col-lg-3 titulo--secundario">Aseguradoras:</div>
                    <div class="col texto--color">First Medical 1-844-347-7800, MMM 1-844-336-3331, Menonita 1-866-600-4753,<br /> Triple-S 1-800-981-1352</div>
                </div>
            </div>
        </div>
        <br />
        <h2 class="titulo--principal2 text-center">Seleccione su Aseguradora de Preferencia</h2>
        <div class="row" style="overflow:hidden">
            <div class="col-md-4">
                <div class="tile">
                    <img class="imgOverlayColor" src="~/wwwroot/assets/img/PrincipalSeleccione4.jpg">
                    <div class="texto--principal centered text-center" style="width:75%;">
                        <span class="align-middle">
                            Búsqueda de Proveedores
                        </span>
                        <br />
                        <a href="~/Principal/BusquedaProveedores" class="btn btn-primary align-text-bottom">MÁS INFO</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="tile">
                    <img class="imgOverlayColor" src="~/wwwroot/assets/img/PrincipalSelecione1.jpg">
                    <div class="texto--principal centered text-center" style="width:75%;">
                        <span class="align-middle">
                            Cambie su Aseguradora (MCO)
                        </span>
                        <br />
                        <a href="~/Principal/CambiarMco" class="btn btn-primary align-text-bottom">MÁS INFO</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="tile">
                    <img class="imgOverlayColor" src="~/wwwroot/assets/img/PrincipalSelecione3.jpg">
                    <div class="texto--principal centered text-center" style="width:75%;">
                        <span class="align-middle">
                            Contacte su Aseguradora (MCO)
                        </span>
                        <br />
                        <a href="~/Principal/ContactaAseguradora" class="btn btn-primary align-text-bottom">MÁS INFO</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

<!--Modal-->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            @*<div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>*@
            <div class="modal-body">
                <div id="news" class="carousel slide" data-ride="carousel">

                    <!-- Indicators -->
                    <ul class="carousel-indicators">
                        <li data-target="#news" data-slide-to="0" class="active"></li>
                        <li data-target="#news" data-slide-to="1"></li>
                    </ul>

                    <!-- The slideshow -->
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img src="~/wwwroot/images/ComunicadoMolina.jpg" width="100%" alt="Molina" />
                            @*<h5 class="modal-title" id="exampleModalLongTitle">@ViewBag.ModalTitle</h5>
                                <br />
                                <p>@ViewBag.ModalMsg</p>
                                <p>@ViewBag.ModalMsg2</p>
                                <br />*@
                        </div>
                        <div class="carousel-item">
                            <img src="~/wwwroot/images/Censo2020.jpg" width="100%" alt="Censo 2020" />
                            <div class="carousel-caption-custom">
                                <a href="@ViewBag.UrlCensos" target="_blank" class="bg-dark text-white">Oprima Aquí</a>
                            </div>
                        </div>
                    </div>

                    <!-- Left and right controls -->
                    <a class="carousel-control-prev" href="#news" data-slide="prev">
                        <span class="carousel-control-prev-icon"></span>
                    </a>
                    <a class="carousel-control-next" href="#news" data-slide="next">
                        <span class="carousel-control-next-icon"></span>
                    </a>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>

<script>
    //var urlCensos = @ViewBag.UrlCensos;
    let enabled = @ViewBag.ModalEnabled.ToString().ToLower();
    if (enabled) {
        $('#exampleModalCenter').modal('toggle');
    }
</script>

EnrollmentPrincipalWebApp/Views/Principal/IndexNA.cshtml
@{
    Layout = "~/Views/Shared/_Layout-Principal-English.cshtml";
    ViewBag.Ruta = @Url.Action("Index", "Principal");
}
<style>
    #Principal {
        position: relative;
        color: white;
    }


    /*.titulo--principal {
        color: #0089b5;
        font-size: 4.2em;
        margin: 0.1em 0 0.5em;
    }*/

    #Principal {
        height: 430px;
        width: 100%;
        overflow: hidden;
    }

    #imgPrincipal {
        min-width: 100%;
        object-fit: cover;
    }

    ul {
        list-style-type: square;
    }

    .carousel-caption-custom {
        position: absolute;
        right: 15%;
        bottom: 105px;
        /*left: 15%;*/
        z-index: 10;
        padding-top: 20px;
        padding-bottom: 20px;
        color: #fff;
        text-align: center;
        text-shadow: 0 1px 2px rgba(0, 0, 0, .6);
    }
</style>

<main>
    <div class="clearfix"></div>
    <div class="container">
        <div class="row" id="Principal">
            <img id="imgPrincipal" class="d-none d-lg-block" src="~/wwwroot/assets/img/Principal.jpg" style="width:100%; max-height:500px; overflow:hidden">
            <img id="imgPrincipal" class="d-none d-md-block d-lg-none" src="~/wwwroot/assets/img/Principal-m.jpg" style="width:100%; max-height:500px; overflow:hidden">
            <img id="imgPrincipal" class="d-md-none" src="~/wwwroot/assets/img/Principal-m2.jpg" style="width:100%; max-height:500px; overflow:hidden">
            <div class="card-body center-left">
                <h2 class="titulo--principal align-middle">
                    <span>YOU CHOOSE</span>
                    <br />
                    <span>your insurer</span>
                </h2>
            </div>
        </div>
        <br />
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-5 col-lg-5  nopadding d-none d-lg-block">
                <img src="~/wwwroot/assets/img/Principal2.jpg" style="width:100%; height:100%;">
            </div>
            <div class="col-md-7 col-lg-7 nopadding">
                <div class="card-body card__principal h-100">
                    <div class="text-left" style="font-size:1em;">
                        <p class="titulo--secundario">The Annual Open Enrollment will be from November 1st thru December 15 2020.</p>
                        <p>During those 45 days you can change insurer, if you want, by <a href=@Url.Action("ChangeMco","Principal")>clicking here.</a> If you wish to stay with your current insurer,  you do not have to make any changes.</p>
                        <ul class="texto--contenido" style="line-height:25px;">
                            <li>If you are only trying to change or update your PMG or PCP, please contact your insurer directly.</li>
                            <li>If your are looking for information about your medical ID card, you can call your insurer or visit their service centers.  (See below for contact information).</li>
                            <li>TTY service is available at 1-888-984-0128.</li>
                            <li>For information related to recertification appointments, please contact the Medicaid Program at 787-641-4224.</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="card-body card__principal">
                <div class="row">
                    <div class="col-xl-2 col-lg-3 titulo--secundario">Insurers:</div>
                    <div class="col texto--color">First Medical 1-844-347-7800, MMM 1-844-336-3331, Menonita 1-866-600-4753,<br /> Triple-S 1-800-981-1352</div>
                </div>
            </div>
        </div>
        <br />
        <h2 class="titulo--principal2 text-center">Choose your Preferred Insurer</h2>
        <div class="row" style="overflow:hidden">
            <div class="col-md-4">
                <div class="tile">
                    <img class="imgOverlayColor" src="~/wwwroot/assets/img/PrincipalSeleccione4.jpg">
                    <div class="texto--principal centered text-center" style="width:75%;">
                        <span class="align-middle">
                            Provider Search
                        </span>
                        <br />
                        <a href=@Url.Action("ProviderSearch","Principal") class="btn btn-primary align-text-bottom">MORE INFO</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="tile">
                    <img class="imgOverlayColor" src="~/wwwroot/assets/img/PrincipalSelecione1.jpg">
                    <div class="texto--principal centered text-center" style="width:75%;">
                        <span class="align-middle">
                            Select your Insurer (MCO)
                        </span>
                        <br />
                        <a href=@Url.Action("ChangeMco","Principal") class="btn btn-primary align-text-bottom">MORE INFO</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="tile">
                    <img class="imgOverlayColor" src="~/wwwroot/assets/img/PrincipalSelecione3.jpg">
                    <div class="texto--principal centered text-center" style="width:75%;">
                        <span class="align-middle">
                            Contact your Insurer (MCO)
                        </span>
                        <br />
                        <a href=@Url.Action("ContactInsurer","Principal") class="btn btn-primary align-text-bottom">MORE INFO</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

<!--Modal-->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            @*<div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>*@
            <div class="modal-body">
                <div id="news" class="carousel slide" data-ride="carousel">

                    <!-- Indicators -->
                    <ul class="carousel-indicators">
                        <li data-target="#news" data-slide-to="0" class="active"></li>
                        <li data-target="#news" data-slide-to="1"></li>
                    </ul>

                    <!-- The slideshow -->
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img src="~/wwwroot/images/ComunicadoMolina.jpg" width="100%" alt="Molina" />
                            @*<h5 class="modal-title" id="exampleModalLongTitle">@ViewBag.ModalTitle</h5>
                                <br />
                                <p>@ViewBag.ModalMsg</p>
                                <p>@ViewBag.ModalMsg2</p>
                                <br />*@
                        </div>
                        <div class="carousel-item">
                            <img src="~/wwwroot/images/Censo2020.jpg" width="100%" alt="Censo 2020" />
                            <div class="carousel-caption-custom">
                                <a href="@ViewBag.UrlCensos" target="_blank" class="bg-dark text-white">Oprima Aquí</a>
                            </div>
                        </div>
                    </div>

                    <!-- Left and right controls -->
                    <a class="carousel-control-prev" href="#news" data-slide="prev">
                        <span class="carousel-control-prev-icon"></span>
                    </a>
                    <a class="carousel-control-next" href="#news" data-slide="next">
                        <span class="carousel-control-next-icon"></span>
                    </a>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>

<script>
    let enabled = @ViewBag.ModalEnabled.ToString().ToLower();
    if (enabled) {
        $('#exampleModalCenter').modal('toggle');
    }
</script>