EnrollmentSystemWebApp/Controllers/DemoController.cs
using Audit.Mvc;
using Common.CustomExtensions;
using Common.Proxies;
using Domain.EntityModel;
using EnrollmentSystemWebApp.Common;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace EnrollmentSystemWebApp.Controllers
{
    [Audit(EventTypeName = "{controller}/{action} ({verb})", IncludeResponseBody = false, IncludeRequestBody = false)]
    public class DemoController : Controller
    {        
        public async Task<ActionResult> Index()
        {
            var transactionId = string.Empty;
            CustomProxyREST<Demo> proxy = new CustomProxyREST<Demo>();
            var response = await proxy.Get(CustomConfigurationLib.CoreAPI_UrlBase,
                                            CustomConfigurationLib.CoreAPI_ServicePreffix,
                                            CustomConfigurationLib.CoreAPI_DemoController,
                                            CustomConfigurationLib.CoreAPI_Demo_Get,
                                            null,
                                            null,
                                            transactionId.NewGUID(),
                                            false,
                                            CustomConfigurationLib.SecondsTimeOutCoreAPI);
            if (response.Code.Equals(CustomConfigurationLib.CodigoExito) || response.Code.Equals(CustomConfigurationLib.CodigoErrorNoDataFound))
            {
                return View(response.listado);
            }
            else
            {
                return Json(response, JsonRequestBehavior.AllowGet);
            }
        }

        // GET: Example/Details/5        
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var transactionId = string.Empty;
            CustomProxyREST<Demo> proxy = new CustomProxyREST<Demo>();
            var response = await proxy.Get(CustomConfigurationLib.CoreAPI_UrlBase,
                                           CustomConfigurationLib.CoreAPI_ServicePreffix,
                                           CustomConfigurationLib.CoreAPI_DemoController,
                                           CustomConfigurationLib.CoreAPI_Demo_Get,
                                           null,
                                           null,
                                           transactionId.NewGUID(),
                                           false,
                                           CustomConfigurationLib.SecondsTimeOutCoreAPI,
                                           id.Value);

            if (response.Code.Equals(CustomConfigurationLib.CodigoExito))
            {
                return View(response.objeto);
            }
            else
            {
                return Json(response);
            }
        }

        // GET: Example/Create        
        public ActionResult Create()
        {
            return View();
        }

        // POST: Example/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "DemoId,Name,CreatedBy,CreatedOn,UpdatedBy,UpdatedOn,Enabled")] Demo demo)
        {
            if (ModelState.IsValid)
            {
                var transactionId = string.Empty;
                CustomProxyREST<Demo, Demo> proxy = new CustomProxyREST<Demo, Demo>();
                var response = await proxy.Post(CustomConfigurationLib.CoreAPI_UrlBase,
                                                CustomConfigurationLib.CoreAPI_ServicePreffix,
                                                CustomConfigurationLib.CoreAPI_DemoController,
                                                CustomConfigurationLib.CoreAPI_Demo_Get,
                                                null,
                                                null,
                                                transactionId.NewGUID(),
                                                false,
                                                CustomConfigurationLib.SecondsTimeOutCoreAPI,
                                                demo);

                if (response.Code.Equals(CustomConfigurationLib.CodigoExito))
                {
                    return View(demo);
                }
                else
                {
                    return RedirectToAction(nameof(Index));
                }
            }

            return View(demo);
        }

        // GET: Example/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var transactionId = string.Empty;
            CustomProxyREST<Demo> proxy = new CustomProxyREST<Demo>();
            var response = await proxy.Get(CustomConfigurationLib.CoreAPI_UrlBase,
                                           CustomConfigurationLib.CoreAPI_ServicePreffix,
                                           CustomConfigurationLib.CoreAPI_DemoController,
                                           CustomConfigurationLib.CoreAPI_Demo_Get,
                                           null,
                                           null,
                                           transactionId.NewGUID(),
                                           false,
                                           CustomConfigurationLib.SecondsTimeOutCoreAPI,
                                           id.Value);

            if (response.Code.Equals(CustomConfigurationLib.CodigoExito))
            {
                return View(response.objeto);
            }
            else
            {
                return Json(response, JsonRequestBehavior.AllowGet);
            }
        }

        // POST: Example/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "DemoId,Name,CreatedBy,CreatedOn,UpdatedBy,UpdatedOn,Enabled")] Demo demo)
        {
            if (ModelState.IsValid)
            {
                var transactionId = string.Empty;
                CustomProxyREST<Demo, Demo> proxy = new CustomProxyREST<Demo, Demo>();
                var response = await proxy.Post(CustomConfigurationLib.CoreAPI_UrlBase,
                                                CustomConfigurationLib.CoreAPI_ServicePreffix,
                                                CustomConfigurationLib.CoreAPI_DemoController,
                                                CustomConfigurationLib.CoreAPI_Demo_Get,
                                                null,
                                                null,
                                                transactionId.NewGUID(),
                                                false,
                                                CustomConfigurationLib.SecondsTimeOutCoreAPI,
                                                demo);

                if (response.Code.Equals(CustomConfigurationLib.CodigoExito))
                {
                    return View(demo);
                }
                else
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(demo);
        }

        // GET: Example/Delete/5        
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var transactionId = string.Empty;
            CustomProxyREST<Demo> proxy = new CustomProxyREST<Demo>();
            var response = await proxy.Get(CustomConfigurationLib.CoreAPI_UrlBase,
                                           CustomConfigurationLib.CoreAPI_ServicePreffix,
                                           CustomConfigurationLib.CoreAPI_DemoController,
                                           CustomConfigurationLib.CoreAPI_Demo_Get,
                                           null,
                                           null,
                                           transactionId.NewGUID(),
                                           false,
                                           CustomConfigurationLib.SecondsTimeOutCoreAPI,
                                           id.Value);

            if (response.Code.Equals(CustomConfigurationLib.CodigoExito))
            {
                return View(response.objeto);
            }
            else
            {
                return Json(response, JsonRequestBehavior.AllowGet);
            }
        }

        // POST: Example/Delete/5        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            //Demo demo = await db.Demoes.FindAsync(id);
            //db.Demoes.Remove(demo);
            //await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                //db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EnrollmentSystemWebApp/Controllers/HomeController.cs
using Audit.Mvc;
using Common;
using Common.Logging;
using EnrollmentSystemWebApp.Helpers;
using Security.API.Model.Response;
using Service.Config;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EnrollmentSystemWebApp.Controllers
{
    [Authorize]    
    public class HomeController : Controller
    {
        private CustomConfigurationLib config;
        public HomeController()
        {
            config = new CustomConfigurationLib();
        }

        public ActionResult Index()
        {
            ViewBag.Title = "Home Page";
            EResponseBase<User_Response_v1> user = (EResponseBase<User_Response_v1>)Session[config.SessionUser];
            ViewBag.Usuario = user.objeto.FirstName;
            ViewBag.listOptions = user.objeto.listOptions;
            ViewBag.BusquedaProveedores = config.SelftService_BusquedaProveedores;
            return View();
        }

        public ActionResult AdditionalResource()
        {
            EResponseBase<User_Response_v1> user = (EResponseBase<User_Response_v1>)Session[config.SessionUser];
            ViewBag.Usuario = user.objeto.FirstName;
            ViewBag.listOptions = user.objeto.listOptions;
            return View();
        }


    }
}

EnrollmentSystemWebApp/Views/Home/Index-bk.cshtml
<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead" data-i18n="DefaultIndex_Subtitle">ASP.NET es un framework web gratuito para crear excelentes sitios web y aplicaciones web utilizando HTML, CSS y JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg" data-i18n="DefaultIndex_LearnMore">Aprender m\u00E1s &raquo;</a></p>
</div>
<div class="row">
    <div class="col-md-4">
        <h2 data-i18n="DefaultIndex_GettingStarted">Iniciando</h2>
        <p data-i18n="DefaultIndex_GettingStarted_subtitle">
           ASP.NET Web API es un marco que facilita la creación de servicios HTTP que lleguen a una amplia gama de clientes, 
           incluidos navegadores y dispositivos móviles.
           ASP.NET Web API es una plataforma ideal para compilar aplicaciones RESTful en .NET Framework.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301870" data-i18n="DefaultIndex_LearnMore">Aprender m\u00E1s &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2 data-i18n="DefaultIndex_GetMoreLibraries">Conseguir más librerias</h2>
        <p data-i18n="DefaultIndex_GetMoreLibraries_subtitle">NuGet es una extensión gratuita de Visual Studio que facilita agregar, eliminar y actualizar bibliotecas y herramientas en proyectos de Visual Studio.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301871" data-i18n="DefaultIndex_LearnMore">Aprender m\u00E1s &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2 data-i18n="DefaultIndex_WebHosting">Alojamiento Web</h2>
        <p data-i18n="DefaultIndex_WebHosting_subtitle">Puede encontrar facilmente una empresa de alojamiento web que ofrezca la combinacion adecuada de caracteristicas y precio para sus aplicaciones.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301872" data-i18n="DefaultIndex_LearnMore">Aprender m\u00E1s &raquo;</a></p>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <p><a class="btn btn-default" href="@Url.Action("Index","Demo")" data-i18n="DefaultIndex_GoDemo">Ir a Demo &raquo;</a></p>
    </div>
</div>

EnrollmentSystemWebApp/Views/Home/Index.cshtml
<link href="~/app-assets/assets/css/CustomCards.css" rel="stylesheet" />
<div class="container">
    <div class="row">
        @foreach (var eachOption in ViewBag.listOptions)
        {

            if (eachOption.Code == "01")
            {
                <div class="col-md-4 col-xs-12">
                    <div class="card horizontal customCard">
                        <div class="ch-grid">
                            <div class="ch-item ch-img-1" onclick="window.location.href = '@Url.Action("SearchPerson", "Person")';">
                                <div class="ch-info ch-info-1">
                                    <img class="img-rounded" src="~/app-assets/assets/images/icon-Search.svg" />
                                </div>
                            </div>
                        </div>
                        <div class="card-stacked">
                            <div class="card-content">
                                <h3 data-i18n="Index_Search_Person">Buscar Beneficiario</h3>
                            </div>
                        </div>
                    </div>
                </div>
            }
            if (eachOption.Code == "02")
            {
                <div class="col-md-4 col-xs-12">
                    <div class="card horizontal customCard">
                        <div class="ch-grid">
                            <div class="ch-item ch-img-3" onclick="window.location.href = '@Url.Action("Settings", "Person")';">
                                <div class="ch-info ch-info-3">
                                    <img class="img-rounded" src="~/app-assets/assets/images/icon-Search.svg" />
                                </div>
                            </div>
                        </div>
                        <div class="card-stacked">
                            <div class="card-content">
                                <h3 data-i18n="Index_Configuration">Configuraci\u00f3n</h3>
                            </div>
                        </div>
                    </div>
                </div>
            }
            if (eachOption.Code == "03")
            {
                <div class="col-md-4 col-xs-12">
                    <div class="card horizontal customCard">
                        <div class="ch-grid">
                            <div class="ch-item ch-img-4">
                                <div class="ch-info ch-info-3" onclick="window.location.href = '@Url.Action("Reports", "Person")';">
                                    <img class="img-rounded" src="~/app-assets/assets/images/icon-Search.svg" />
                                </div>
                            </div>
                        </div>
                        <div class="card-stacked">
                            <div class="card-content">
                                <h3 data-i18n="Navbar_searh_report">Reports</h3>
                            </div>
                        </div>
                    </div>
                </div>
            }
            if (eachOption.Code == "04")
            {
                <div class="col-md-4 col-xs-12">
                    <div class="card horizontal customCard">
                        <div class="ch-grid">
                            <div class="ch-item ch-img-2" onclick="window.location.href = '@Url.Action("AdditionalResource", "Home")';">
                                <div class="ch-info ch-info-2">
                                    <img class="img-rounded" src="~/app-assets/assets/images/icon-Search.svg" />
                                </div>
                            </div>
                        </div>
                        <div class="card-stacked">
                            <div class="card-content">
                                <h3 data-i18n="Index_Conselor_Additional_Resources">Recursos Adicionales del Counselor</h3>
                            </div>
                        </div>
                    </div>
                </div>
            }

        }

        @*<div class="col-md-4 col-xs-12">
            <div class="card horizontal customCard">
                <div class="ch-grid">
                    <div class="ch-item ch-img-10">
                        <div class="ch-info ch-info-10" onclick="window.location.href = '@Url.Action("Rejects", "Enrollment")';">
                            <img class="img-rounded" src="~/app-assets/assets/images/icon-Search.svg" />
                        </div>
                    </div>
                </div>
                <div class="card-stacked">
                    <div class="card-content">
                        <h3 data-i18n="Navbar_searh_reject">Gesti\u00f3n de Rechazos</h3>
                    </div>
                </div>
            </div>
        </div>*@
        <div class="col-md-4 col-xs-12">
            <div class="card horizontal customCard">
                <div class="ch-grid">
                    <div class="ch-item ch-img-11">
                        <div class="ch-info ch-info-10" onclick="window.open('@ViewBag.BusquedaProveedores','_blank');">
                            <img class="img-rounded" src="~/app-assets/assets/images/icon-Search.svg" />
                        </div>
                    </div>
                </div>
                <div class="card-stacked">
                    <div class="card-content">
                        <h3 data-i18n="Navbar_searh_searchpcp">Buscar PCP</h3>
                    </div>
                </div>
            </div>
        </div>
        @*<div class="col-md-4 col-xs-12">
            <div class="card horizontal customCard">
                <div class="ch-grid">
                    <div class="ch-item ch-img-5" onclick="window.location.href = '@Url.Action("EnrollmentCompare", "Compare")';">
                        <div class="ch-info ch-info-1">
                            <img class="img-rounded" src="~/app-assets/assets/images/icon-Search.svg" />
                        </div>
                    </div>
                </div>
                <div class="card-stacked">
                    <div class="card-content">
                        <h3 data-i18n="Index_Search_PMP">Buscar PCP</h3>
                    </div>
                </div>
            </div>
        </div>*@
    </div>
</div>

@*<div class="row">
        <div class="col-md-4 col-xs-12">
            <div class="card horizontal customCard">
                <div class="ch-grid">
                    <div class="ch-item ch-img-4">
                        <div class="ch-info ch-info-4">
                            <img src="~/app-assets/assets/images/icon-Navigation.svg" />
                        </div>
                    </div>
                </div>
                <div class="card-stacked">
                    <div class="card-content">
                        <h3 data-i18n="Index_Search_PCP/PCM">Buscar PCP/PMG</h3>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4 col-xs-12">
            <div class="card horizontal customCard">
                <div class="ch-grid">
                    <div class="ch-item ch-img-5">
                        <div class="ch-info ch-info-5">
                            <img src="~/app-assets/assets/images/icon-Report.svg" />
                        </div>
                    </div>
                </div>
                <div class="card-stacked">
                    <div class="card-content">
                        <h3 data-i18n="Index_Reporting">Reportes</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>*@
<script src="~/app-assets/assets/js/CustomCards.js"></script>
<script>
    $("#home").attr({
        class: "active"
    });
</script>